openapi: 3.0.3
info:
  description: Slug Finance API
  version: 0.1.0
  title: Finance API
servers:
  - url: '/'
paths:
  '/v0/ticker/{id}':
    parameters:
      - name: id
        in: path
        description: Stock Ticker
        required: true
        schema:
          type: string
          format: string
    get:
      description: Returns the email identified by the id
      responses:
        '200':
          description: Email found
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Stock'
        '404':
          description: Stock ticker not found
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Stock:
      type: object
      additionalProperties: false
      required:
        - symbol
        - price
        - change
        - dailyChange
      properties:
        symbol:
          type: string
        price:
          type: string
        change:
          type: string
        dailyChange:
          type: string